version: "3"
services:
  diglet-bot-db:
    container_name: digletbot-db
    image: mariadb:11.3.2
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "diglet-bot"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ./provisioning/local-data:/var/lib/mysql
