services:
  diglet-bot-db:
    container_name: digletbot-db
    image: mariadb:11.4.2
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "digletbot"
    volumes:
      - ./provisioning/local-data:/var/lib/mysql
