services:
# Uncommented on server
#  digletbot:
#    container_name: digletbot
#    image: maelstromeous/applications:digletbot-latest
#    env_file: digletbot.env
#    restart: unless-stopped
#    depends_on:
#      - digletbot-db
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
  digletbot-db:
    container_name: digletbot-db
    image: mariadb:12.0.2
    env_file: digletbot-db.env
    restart: unless-stopped
    ports:
      - "3307:3306"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
#      - ./data:/var/lib/mysql
      - ./provisioning/local-data/db:/var/lib/mysql
