export default () => ({
  devUserId: process.env.DISCORD_DEVUSER_ID,
  channels: {
    albionRegistration: process.env.CHANNEL_ALBION_REGISTRATION,
    albionUSRoles: process.env.CHANNEL_ALBION_US_ROLES,
    albionEURoles: process.env.CHANNEL_ALBION_EU_ROLES,
    albionUSAnnouncements: process.env.CHANNEL_ALBION_US_ANNOUNCEMENTS,
    albionEUAnnouncements: process.env.CHANNEL_ALBION_EU_ANNOUNCEMENTS,
    albionScans: process.env.CHANNEL_ALBION_SCANS,
    ps2Verify: process.env.CHANNEL_PS2_VERIFY,
    ps2Private: process.env.CHANNEL_PS2_PRIVATE,
    ps2HowToRankUp: process.env.CHANNEL_PS2_HOW_TO_RANK_UP,
    ps2Scans: process.env.CHANNEL_PS2_SCANS,
  },
  roles: {
    albionUSMember: process.env.ROLE_ALBION_US_MEMBER,
    albionEUMember: process.env.ROLE_ALBION_EU_MEMBER,
    albionUSRegistered: process.env.ROLE_ALBION_US_REGISTERED,
    albionEURegistered: process.env.ROLE_ALBION_EU_REGISTERED,
    albionUSAnnouncements: process.env.ROLE_ALBION_US_ANNOUNCEMENTS,
    albionEUAnnouncements: process.env.ROLE_ALBION_EU_ANNOUNCEMENTS,
    ps2Verified: process.env.ROLE_PS2_VERIFIED,
    ps2Zealot: process.env.ROLE_PS2_ZEALOT,
  },
});
