version: "3"
services:
  diglet-bot:
    container_name: digletbot
    image: maelstromeous/applications:digletbot-latest
    env_file: docker-digletbot.env # see .env.example
    restart: unless-stopped
    depends_on:
      - diglet-bot-db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  diglet-bot-db:
    container_name: digletbot-db
    image: mariadb:11.3.2
    env_file: docker-digletbot-db.env
    restart: unless-stopped
    ports:
      - "3307:3306"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ./data:/var/lib/mysql
