---
name: Build & Publish

on:
  workflow_call:
    inputs:
      version:
        description: 'Version of the release'
        type: string
        required: true
        default: '0.0.0'
      store-path:
        description: 'Path to the pnpm store'
        type: string
        required: true
        default: ''

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: true

      - uses: actions/cache@v3
        name: Pull pnpm cache
        with:
          path: ${{ github.event.inputs.store-path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            maelstromeous/applications:digletbot-${{ github.event.inputs.version }}
            maelstromeous/applications:digletbot-latest
