name: CI

on:
  push:
    branches: [main]

jobs:
  steps:
    - release:
      name: Create Release
      uses: ./.github/actions/release

    - deploy:
      needs: release
      with:
        version: ${{ needs.release.outputs.version }}
      uses: ./.github/actions/build-publish
