name: CI

on:
  push:
    branches: [main]

jobs:
  node:
    uses: ./.github/workflows/node.yml

  release:
    needs: node
    name: Create Release
    uses: ./.github/workflows/release.yml

  deploy:
    needs: [release, node]
    with:
      version: ${{ needs.release.outputs.version }}
    uses: ./.github/workflows/build-publish.yml
    secrets: inherit
