name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/node.yml

  release:
    needs: build
    uses: ./.github/workflows/release.yml

  deploy:
    needs: [build, release]
    with:
      version: ${{ needs.release.outputs.version }}
    uses: ./.github/workflows/build-publish.yml
    secrets: inherit
