name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-and-test-main.yml
    secrets: inherit

  release:
    name: Create Release
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit

  publish:
    name: Build & Publish container
    needs: [build, release]
    with:
      version: ${{ needs.release.outputs.version }}
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
