name: Production Deployment

on:
  push:
    branches: [main]
    # Ensures only actual code changes trigger the workflow, otherwise we don't want to create a full on build.
    paths:
      - '.github/workflows/**'     # GitHub Actions workflows
      - 'src/**'                   # Source code directory
      - 'package.json'             # Node.js dependencies and scripts
      - 'pnpm-lock.yaml'           # Lock file for Node.js dependencies
      - '.eslint*'                 # ESLint configuration
      - 'Dockerfile'               # Dockerfile
      - 'docker-compose.yml'       # Docker Compose file
      - 'entrypoint.sh'            # Entrypoint script for Docker container
      - 'jest.config.js'           # Jest configuration
      - 'mikro-orm.config.ts'      # MikroORM configuration
      - 'sonar-project.properties' # SonarQube configuration'

jobs:
  build:
    name: Build & Test application
    uses: ./.github/workflows/build-and-test-main.yml
    secrets: inherit

  release:
    name: Create Release
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit

  publish:
    name: Build & Publish container
    needs: [build, release]
    with:
      version: ${{ needs.release.outputs.version }}
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  trigger-deploy:
    name: Trigger deployment
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  trigger-deploy:
    name: Trigger deployment
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
