name: CI

on:
  push:
    branches: [main]

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/release.yml

  node:
    needs: release
    uses: ./.github/workflows/node.yml

  deploy:
    needs: [release, node]
    with:
      version: ${{ needs.release.outputs.version }}
      pnpm-cache: ${{ needs.node.outputs.pnpm-cache }}
    uses: ./.github/workflows/build-publish.yml
    secrets: inherit
