name: CI

on:
  push:
    branches: [main]

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/release.yml

  node:
    needs: release
    uses: ./.github/workflows/node.yml
    secrets: inherit

  deploy:
    needs: [release, node]
    with:
      version: ${{ jobs.release.outputs.version }}
      store-path: ${{ jobs.node.outputs.store-path }}
    uses: ./.github/workflows/build-publish.yml
    secrets: inherit
