name: CI

on:
  push:
    branches: [main]

jobs:
  release:
    needs: checkout
    name: Create Release
    uses: ./.github/workflows/release.yml
    runs-on: ubuntu-latest

  deploy:
    needs: release
    with:
      version: ${{ needs.release.outputs.version }}
    uses: ./.github/workflows/build-publish.yml
    runs-on: ubuntu-latest
