---
name: Build & Publish

on:
  workflow_call:
    inputs:
      version:
        description: 'Version of the release'
        type: string
        required: true
        default: '0.0.0'

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - uses: actions/cache@v4
        name: Pull pnpm cache
        with:
          path: node_modules
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64
          context: .
          push: true
          build-args: |
            VERSION=${{ inputs.version }}
          tags: |
            maelstromeous/applications:digletbot-${{ inputs.version }}
            maelstromeous/applications:digletbot-latest
