---
name: PR Proposed Version

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Simulate new version
        id: version
        uses: phips28/gh-action-bump-version@master
        with:
          skip-commit: true
          skip-push: true

      # Echo what version this would be
      - name: Echo new version
        run: "echo 'New Version: ${{ steps.version.outputs.newTag }}'"
