name: PR Tests
on:
  pull_request:

jobs:
  test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test-pr.yml
    secrets: inherit
  version:
    name: Proposed version
    uses: ./.github/workflows/pr-version.yaml
